### ISSUE TITLE
Cannot use GenerateCtrfReport and documentation issue

### ISSUE THREAD

**Issue by NinjaQaSa** [ctrf-io/cypress-ctrf-json-reporter#14]
Hi, 

I've been going through the documentation trying to implement the reporter and I've run into the below issue.

The documentation says we must run: 

`npm install --save-dev cypress-ctrf-json-reporter`

however, in the import/require statement, it asks us to import: `'cypress-ctrf-json-report'` - note the 'er' is missing - this is when comparing to the package name.

The initial import asks us to import `generateCtrfJsonReport`, but this method does not exist in the code as far as I can see. Doing a brief run through, the code has the method `GenerateCtrfReport` exported instead of `generateCtrfJsonReport`

When I make the above updates with importing, I run into this error:

![image](https://github.com/ctrf-io/cypress-ctrf-json-reporter/assets/163893971/25e18533-7b9c-4560-8ae9-e7db25a8cfce)

Please let me know if I am missing out on anything or using this incorrectly. It will be greatly appreciated.

**Comment by NinjaQaSa** [comment]
This is how I fixed it:
![image](https://github.com/ctrf-io/cypress-ctrf-json-reporter/assets/163893971/bd87998c-1dc0-42a8-a5fa-8313c368dd66)

**Comment by NinjaQaSa** [comment]
fixed as per previous screenshot

**Comment by Ma11hewThomas** [comment]
Thanks for your feedback @NinjaQaSa - the documentation has been amended
