### ISSUE TITLE
JSON result is being overwritten on each test

### ISSUE THREAD

**Issue by feliperaul** [ctrf-io/cypress-ctrf-json-reporter#16]
First of all, thank for this library, it's exactly what we were after!

However, when starting the test suite with `yarn run cypress run --browser chrome --project ./test`, we notice that the result file get's overwritten after each test runs; this means that the resulting json has an array `tests`, but it only contains the last test run.

Also, I think the README is not updated regarding the defaults; the default filename that's being generated is `test/after-spec-results`, and not `ctrf/ctrf-report.json` as per the docs.

**Comment by Ma11hewThomas** [comment]
Thanks for your feedback, please can you try version 0.0.8

As you are running command with --project ./test, the project root is ./test so the output directory should be created inside ./test

With default settings the final report should be saved at ./test/ctrf/ctrf-report.json

Please can you confirm if this is the case? 

If you still have issues, are you able to share cypress version, config settings and generated report (sensitive info removed)
