### ISSUE TITLE
feat: report merge functionality

### ISSUE THREAD

**Issue by viktorgagaleski** [ctrf-io/cypress-ctrf-json-reporter#18]
It would be nice if we can have an option to merge the JSON reports, especially when running as part of a pipeline.

BTW I have to express kudos for the project, as it really helped me to report flaky tests for Cypress. I tried almost everything, and none of the reporters work as this one, thanks for that!

**Comment by Ma11hewThomas** [comment]
Great to hear! The [ctrf cli merge method](https://github.com/ctrf-io/ctrf-cli?tab=readme-ov-file#merge) might be what you are looking for
