### ISSUE TITLE
Unable to use with multiple plugins that use the same event

### ISSUE THREAD

**Issue by AS-knampally** [ctrf-io/cypress-ctrf-json-reporter#19]
Only the report folder is generated; the JSON report is not generated

**Comment by Ma11hewThomas** [comment]
I can’t recreate this, please can you share the following:
CTRF Reporter version
CTRF reporter config
Cypress version 
Any logs generated by CTRF
The cypress default reporter summary output, tests passed etc

**Comment by Ma11hewThomas** [comment]
please see https://github.com/ctrf-io/cypress-ctrf-json-reporter?tab=readme-ov-file#handling-multiple-plugins-in-cypress

Thanks
